title: 機械学習発展 (実践)
author: Tatsuya Yatagawa
copyright: "CC BY-NC-SA 4.0, 2023-2024"
logo: ""

description: >-
  Pythonを用いて、画像認識と機械学習の実践的な利用法について学ぶ

exclude_patterns:
  - _build
  - data
  - modules
  - autograding
  - templates
  - Thumbs.db
  - .DS_Store
  - .pytest_cache
  - .mypy_cache
  - .jupyter_cache
  - .pytest_cache
  - "**.ipynb_checkpoints"

only_build_toc_files: true

execute:
  allow_errors: false
  execute_notebooks: cache
  cache: ./.jupyter_cache
  timeout: 180
  exclude_patterns:
    - "scikit-learn.ipynb"
    - "exercise-sudoku.ipynb"
    - "feature-extraction.ipynb"
    - "deep-learning.ipynb"
    - "othello-agent.ipynb"
    - "exercise-othello.ipynb"

# HTML-specific settings
html:
  favicon: ""
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: true
  home_page_in_navbar: false
  use_multitoc_numbering: true
  base_url: "/1284-sds-advml"

# Interact link settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: ""
  jupyterhub_url: ""
  thebe: false
  colab_url: "https://colab.research.google.com"

# Launch button settings
repository:
  url: https://github.com/tatsy-classes/1284-sds-advml
  path_to_book: ""
  branch: master

# Sphinx
sphinx:
  recursive_update: true
  extra_extensions:
    - sphinxcontrib.sass
  config:
    language: ja
    numfig: true
    math_numfig: true
    numfig_secnum_depth: 1
    # MathJax
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js
    mathjax3_config:
      loader:
        load: ["[tex]/physics", "[tex]/boldsymbol"]
      tex:
        packages: { "[+]": ["physics", "boldsymbol"] }
    # BibTeX
    bibtex_reference_style: author_year
    # Theme
    html_theme_options:
      pygments_light_style: gotthard-light
      pygments_dark_style: material
    # sphinxcontrib.sass
    sass_src_dir: "_assets"
    sass_out_dir: "_static"
    sass_targets: { "custom.scss": "custom.css" }
    html_css_files: ["custom.css"]
    # Others
    suppress_warnings: ["mystnb.unknown_mime_type"]

bibtex_bibfiles:
  - "references.bib"

# MyST options
parse:
  myst_footnote_transition: false
  myst_enable_extensions:
    - amsmath
    - dollarmath
    - colon_fence

# LaTeX
latex:
  latex_engine: "xelatex"
  use_jupyterbook_latex: true
