title: 機械学習発展 (実践)
author: Tatsuya Yatagawa
# logo: 'qe-logo-large.png'

# Short description about the book
description: >-
  A brief introduction to Python programming for scientific applications.

execute:
  execute_notebooks: cache
  timeout: 180

# HTML-specific settings
html:
  home_page_in_navbar: false
  use_multitoc_numbering: false

# Interact link settings
notebook_interface: "notebook"

# Launch button settings
repository:
  url: https://github.com/tatsy/1284-sds-ml-advanced
  path_to_book: "contents"

# Sphinx
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

parse:
  myst_footnote_transition: False
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
# binder:
#   binderhub_url               : "https://mybinder.org"
#   text                        : "Launch binder"

# LaTeX settings
# bibtex_bibfiles:
#    - _bibliography/references.bib
# latex:
#   latex_engine                : "xelatex"
#   latex_documents:
#     targetname: book.tex

