title: 機械学習発展 (実践)
author: Tatsuya Yatagawa
# logo: 'qe-logo-large.png'

description: >-
  A brief introduction to Python programming for scientific applications.

exclude_patterns:
  - _build
  - data
  - templates
  - Thumbs.db
  - .DS_Store
  - .pytest_cache
  - .mypy_cache
  - "**.ipynb_checkpoints"

only_build_toc_files: true

execute:
  execute_notebooks: cache
  timeout: 180

# HTML-specific settings
html:
  home_page_in_navbar: false
  use_multitoc_numbering: false

# Interact link settings
notebook_interface: "notebook"

# Launch button settings
repository:
  url: https://github.com/tatsy/1284-sds-ml-advanced
  path_to_book: "contents"

# Sphinx
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    bibtex_reference_style: author_year

bibtex_bibfiles:
  - "references.bib"

# MyST options
parse:
  myst_footnote_transition: False
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath

# LaTeX
latex:
  latex_engine: "xelatex"
  use_jupyterbook_latex: true
