name: advml
channels:
  - defaults
  - pytorch
dependencies:
  - python^=3.9
  - numpy
  - scipy
  - opencv
  - opencv-contrib
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - openpyxml
  - pandas
  - pytorch^=1.10.0
  - tqdm
  - networkx
  - ffmpeg
  - gymnasium[classic-control]
  - pip
  - pip:
    - jupyterlab
