name: advml
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - opencv
  - matplotlib
  - seaborn
  - scikit-learn
  - pandas
  - tqdm
  - networkx
  - pip
  - pip:
    - jupyterlab
