name: advml
channels:
  - defaults
  - pytorch
dependencies:
  - python>=3.9,<3.12
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - openpyxl
  - opencv
  - matplotlib
  - seaborn
  - pytorch>=1.10.0
  - torchvision>=0.11.0
  - tqdm
  - networkx
  - ffmpeg
  - gymnasium[classic-control]
  - pip
  - pip:
    - opencv-contrib-python
    - openpyxml
    - jupyterlab
    - opencv-contrib-python
