[tool.poetry]
name = "sds-adv-ml"
version = "0.1.0"
description = ""
authors = ["Tatsuya Yatagawa <tatsy.mail@gmail.com>"]
readme = "README.md"
packages = [{ include = "advml" }, { include = "advml/reversi" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.11.0"
numpy = "^1.25.0"
scipy = "^1.11.1"
scikit-learn = "^1.2.2"
matplotlib = "^3.7.1"
pandas = "^2.0.3"
seaborn = "^0.12.2"
opencv-python = "^4.8.0.74"
networkx = "^3.1"
openpyxl = "^3.1.2"
tqdm = "^4.66.1"

[tool.poetry.group.dev.dependencies]
pyproject-flake8 = "^6.0.0"
mypy = "^1.4.1"
isort = "^5.12.0"
black = "^23.3.0"
jupyter-book = "^0.15.1"
jupyterlab = "^4.0.0"
jupyterlab-code-formatter = "^2.2.1"
pytest = "^7.4.0"
ipywidgets = "^8.1.0"
jupyterlab-widgets = "^3.0.8"
nodejs = "^0.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
length_sort = "True"
line_length = 99

[tool.mypy]
python_version = 3.9
follow_imports = "silent"
disallow_any_generics = "True"
strict_optional = "True"
check_untyped_defs = "True"
allow_redefinition = "True"

[tool.flake8]
max-line-length = 99
ignore = "Q000,E127,E203,E402,W503,W504"

[tool.black]
target-version = ["py39", "py310", "py311"]
line-length = 99
