name: Build modules

on:
  push:
    branches:
      - master
      - dev
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os:
          [
            "windows-latest",
            "macos-latest",
            "macos-latest-large",
            "ubuntu-latest",
          ]
        python-version-major: [3]
        python-version-minor: [9]
    env:
      python-version: ${{ format('{0}.{1}', matrix.python-version-major, matrix.python-version-minor) }}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.MY_PAT }}
      - name: Install Poetry
        run: |
          pipx install poetry
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}
          cache: "poetry"
          cache-dependency-path: "pyproject.toml"
      - name: Upgrade Poetry
        run: |
          pip install --upgrade poetry
      - name: Install dependencies
        run: |
          poetry build -f wheel
          poetry install
      - name: Check
        run: poetry run python -c "import othello"

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*.whl
          draft: false
          prerelease: false
