name: Miniconda

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.MY_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Miniconda
        run: |
          $CONDA/bin/conda env create --file environment.yaml

      - name: Check Installation
        run: |
          python -c "import torch"
