name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: git submodule update --init --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update Pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Poetry
        run: |
          python -m pip install poetry

      - name: Install packages
        run: |
          poetry install --no-interaction

      - name: Build
        run: poetry run jb build --all .

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build
