name: GitHub Pages

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    strategy:
      matrix:
        python-version: ["3.10"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.MY_PAT }}

      - name: Install FFmpeg
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg

      - name: Cache Jupyter execution
        uses: actions/cache@v3
        with:
          path: .jupyter_cache
          key: ${{ matrix.os }}-jupyter-${{ hashFiles('**/*.ipynb') }}
          restore-keys: |
            ${{ matrix.os }}-jupyter-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Poetry
        run: |
          pipx install poetry==1.8.0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install packages
        run: |
          poetry install
          poetry install --all-extras

      - name: Build
        run: poetry run jb build --all .

      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_build/html/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Github Pages deployment
        id: deployment
        uses: actions/deploy-pages@v4
