name: Python environment

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.MY_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create venv (Linux/MacOS)
        if: "!contains(matrix.os, 'windows')"
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          python -c "import torch"

      - name: Create venv (Windows)
        if: "contains(matrix.os, 'windows')"
        run: |
          python -m venv .venv
          ./.venv/Scripts/activate
          pip install -r requirements.txt
          python -c "import torch"
